# Generated by Django 5.0.3 on 2024-03-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0006_article_category_article_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='bazaapp.category', verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name="Bo'lim Turlari"),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
