# Generated by Django 5.0.3 on 2024-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0008_remove_category_parent_remove_category_slug_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, null=True, unique=True, verbose_name='Proyekt Statusi')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Jarayon',
                'verbose_name_plural': 'Jarayonlar',
            },
        ),
    ]
