# Generated by Django 5.0.3 on 2024-04-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0010_alter_status_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Xizmat Turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Xizmat Turi',
                'verbose_name_plural': 'Xizmat Turlari',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='headcategory',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bazaapp.headcategory'),
        ),
    ]
