# Generated by Django 5.0.3 on 2024-04-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0011_headcategory_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ism Familya'),
        ),
    ]
