# Generated by Django 5.0.3 on 2024-04-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0012_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.AddField(
            model_name='headcategory',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ism Familya'),
        ),
    ]
