# Generated by Django 5.0.3 on 2024-04-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0013_remove_category_owner_headcategory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='headcategory',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bazaapp.headcategory'),
        ),
    ]
