# Generated by Django 4.2.11 on 2024-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0015_alter_category_options_alter_headcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Telegram Guruh')),
                ('group_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='Telegram Guruh IDsi')),
            ],
            options={
                'verbose_name': 'Telegram Guruh',
                'verbose_name_plural': 'Telegram Guruhlar',
            },
        ),
        migrations.AlterField(
            model_name='status',
            name='deadline',
            field=models.CharField(blank=True, default='Deadline Vaqti', max_length=15, null=True),
        ),
    ]
