# Generated by Django 4.2.11 on 2024-04-12 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0016_telegramgroups_alter_status_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='deadline',
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bazaapp.telegramgroups'),
        ),
    ]
