# Generated by Django 4.2.11 on 2024-04-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0017_remove_status_deadline_projects_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bazaapp.status'),
        ),
    ]
