# Generated by Django 4.2.11 on 2024-04-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0018_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroups',
            name='headgroups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bazaapp.headcategory'),
        ),
    ]
