# Generated by Django 4.2.11 on 2024-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaapp', '0019_telegramgroups_headgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='deadline_time',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Proyekt vaqti'),
        ),
    ]
